INSERT INTO `ROLE` (`ID`, `NAME`, `UPDATE_TIME`) VALUES (1, 'ROLE_USER', NOW());
INSERT INTO `ROLE` (`ID`, `NAME`, `UPDATE_TIME`) VALUES (2, 'ROLE_ADMIN', NOW());
INSERT INTO `ROLE` (`ID`, `NAME`, `UPDATE_TIME`) VALUES (3, 'ROLE_IT_ENGINEER', NOW());
INSERT INTO `ROLE` (`ID`, `NAME`, `UPDATE_TIME`) VALUES (4, 'ROLE_HR', NOW());
INSERT INTO `ROLE` (`ID`, `NAME`, `UPDATE_TIME`) VALUES (5, 'ROLE_HEADHUNTER', NOW());