INSERT INTO `USER` (`ID`, `LOGIN_NAME`, `REAL_NAME`, `PASSWORD`, `TYPE`, `UPDATE_TIME`) VALUES (1, 'admin@funshion.com', 'admin', '123456', 0, NOW());
INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (1, 1);
INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (1, 2);